import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "@/css/globals.css";
import { Toaster } from "react-hot-toast";

const quicksand = Quicksand({
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Riven BD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
